//
//  ListOfDepartment.swift
//  MonBonCoin
//
//  Created by Nicolas Schena on 30/10/2023.
//

import Foundation

// Not all of them are available on the DataBase
// Can be update later
struct Department {
    let listOfDepartment = [
        "01" : "Ain",
        "02" : "Aisne",
        "03" : "Allier",
        "04" : "Alpes-De-Haute-Provence",
        "05" : "Hautes-Alpes",
        "06" : "Alpes-Maritimes",
        "07" : "Ardèche",
        "08" : "Ardennes",
        "09" : "Ariège",
        "10" : "Aube",
        "11" : "Aude",
        "12" : "Aveyron",
        "13" : "Bouches-Du-Rhône",
        "14" : "Calvados",
        "15" : "Cantal",
/*        "16" : "Charente",
        "17" : "Charente-Maritime",
        "18" : "Cher",
        "19" : "Corrèze",
        "2A" : "Corse-Du-Sud",
        "2B" : "Haute-Corse",
        "21" : "Côte-D’or",
        "22" : "Côtes D’armor",
        "23" : "Creuse",
        "24" : "Dordogne",
        "25" : "Doubs",
*/        "26" : "Drôme",/*
        "27" : "Eure",
        "28" : "Eure-Et-Loir",
        "29" : "Finistère",
        "30" : "Gard",
        "31" : "Haute-Garonne",
        "32" : "Gers",
        "33" : "Gironde",
        "34" : "Hérault",
        "35" : "Ille-Et-Vilaine",
        "36" : "Indre",
        "37" : "Indre-Et-Loire",
        "38" : "Isère",
*/        "39" : "Jura",/*
        "40" : "Landes",
        "41" : "Loir-Et-Cher",
        "42" : "Loire",
        "43" : "Haute-Loire",
        "44" : "Loire-Atlantique",
        "45" : "Loiret",
        "46" : "Lot",
        "47" : "Lot-Et-Garonne",
        "48" : "Lozère",
        "49" : "Maine-Et-Loire",
        "50" : "Manche",
        "51" : "Marne",
        "52" : "Haute-Marne",
        "53" : "Mayenne",
        "54" : "Meurthe-Et-Moselle",
        "55" : "Meuse",
        "56" : "Morbihan",
        "57" : "Moselle",
        "58" : "Nièvre",
        "59" : "Nord",
        "60" : "Oise",
        "61" : "Orne",
        "62" : "Pas-De-Calais",
        "63" : "Puy-De-Dôme",
        "64" : "Pyrénées-Atlantiques",
        "65" : "Hautes-Pyrénées",
        "66" : "Pyrénées-Orientales",
        "67" : "Bas-Rhin",
        "68" : "Haut-Rhin",
        "69" : "Rhône",
        "70" : "Haute-Saône",
        "71" : "Saône-Et-Loire",
        "72" : "Sarthe",
        "73" : "Savoie",
        "74" : "Haute-Savoie",
*/        "75" : "Paris",/*
        "76" : "Seine-Maritime",
        "77" : "Seine-Et-Marne",
        "78" : "Yvelines",
        "79" : "Deux-Sèvres",
        "80" : "Somme",
        "81" : "Tarn",
        "82" : "Tarn-Et-Garonne",
        "83" : "Var",
        "84" : "Vaucluse",
        "85" : "Vendée",
        "86" : "Vienne",
        "87" : "Haute-Vienne",
        "88" : "Vosges",
        "89" : "Yonne",
        "90" : "Territoire De Belfort",
        "91" : "Essonne",
        "92" : "Hauts-De-Seine",
*/        "93" : "Seine-Saint-Denis",/*
        "94" : "Val-De-Marne",
        "95" : "Val-D’oise",
        "971" : "Guadeloupe",
        "972" : "Martinique",
        "973" : "Guyane",
        "974" : "La Réunion",
        "976" : "Mayotte"*/
    ]
}
